STORAGE_SQLITE_NAME = "ifome.db"
STORAGE_SQLITE_PATH = f"src/infrastructure/config/{STORAGE_SQLITE_NAME}"
BUY_QUEUE = "buy"
HOST_MESSAGE_BROKER = "localhost"
STORAGE_TYPE = "mysql"
MESSAGE_BROKER_TYPE = "rabbitmq"
